version: '3.9'

services:
  frontend:
    build:
      context: ./Client
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./Client/frontend/:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000/
    networks:
      - app-network

  # backend:
  #   build:
  #     context: ./Server
  #   container_name: backend
  #   ports:
  #     - "3001:3000"
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_HOST=postgres_db
  #     - DATABASE_PORT=5432
  #     - DATABASE_USER=postgres
  #     - DATABASE_PASSWORD=postgres
  #     - DATABASE_NAME=mydatabase
  #   volumes:
  #     - ./Server/backend:/app
  #   networks:
  #     - app-network

  # db:
  #   image: postgres:15
  #   container_name: postgres_db
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=mydatabase
  #   volumes:
  #     - /home/adihaj/Desktop/Purience/Database:/var/lib/postgresql/data
  #   networks:
  #     - app-network

  # adminer:
  #   container_name: adminer
  #   image: adminer
  #   ports:
  #     - "8081:8080"
  #   networks:
  #     - app-network
  #   restart: always

networks:
  app-network:
    driver: bridge
